### ISSUE TITLE
github actions deploying branches

### ISSUE THREAD

**Issue by clux** [clux/probes#8]
despite having deploy pipeline limited to `main`:

```yaml
name: Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
```

we still somehow managed to pre-publish a post from https://github.com/clux/probes/pull/7 to clux.dev

is this a me issue or github actions?
